blank_issues_enabled: false
contact_links:
  - name: Alantec Support & Community
    url: https://github.com/Mente-Calibrada
    about: Please reach out for community support and architecture guidelines.
